# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    reset_simulators
    swift
    capture_screenshots(workspace: "RushMe.xcworkspace", scheme: "RushMeUITests")
    upload_to_app_store(skip_binary_upload: true, skip_metadata: true)
  end
  lane :uploadscreenshots do
    upload_to_app_store
  end
  lane :swift do
	ensure_swift_version(version: "Apple Swift version 4.2")
  end
  lane :beta do
#    sync_code_signing(type: "appstore")   
 # see code signing guide for more information
#    increment_build_number 
# automatically increment by one
    build_app(scheme: "RushMe")
    upload_to_testflight
  end
end

