module: SwiftKuery
author: IBM
github_url: https://github.com/IBM-Swift/Swift-Kuery/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, SwiftKuery.xcodeproj, -target, SwiftKuery, LIBRARY_SEARCH_PATHS=.build/debug]
